--- 
title: "APA Statement using Resampling Techniques for GLM using R"
author: "Ekarin E. Pongpipat, Phillip F. Agres, Paulina Skolasinska, Yuefeng Huang, Jane Lung"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This book is a reference on how to perform resampling techniques (e.g., bootstrapping and permutation testing) to write a more informed APA statement."
subtitle: "This book is a reference on how to perform resampling techniques (e.g., bootstrapping and permutation testing) to write a more informed APA statement."
---

# Introduction

Note: This bookdown was creating during Brainhack-Dallas as a project to work with bookdown, review bootstrapping and permutation testing, and write out this APA statement.

## APA Statement (Bare Minimum)

Currently, the APA statement includes: 

- Estimate
- Name of Statistic
- Degrees of Freedom (df)
- Statistical Value
- *p*-value

## More Informative APA Statement

However, sometimes we want more information such as effect sizes or confidence intervals. Thus, we should also consider including the following: 

- Estimate and its Confidence Interval (CI)
- Name of Statistic
- Degrees of Freedom (df)
- Statistical Value
- Mean Squared Error (MSE)
- Adjusted R^2 and its CI
- Permutated P-Value

## Code Structure

The code could definitely be more efficient. However, we have written the code this way because we believe that the code helps conceptually represent what is happening when you bootstrap or permute.